/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Artifact = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'name' : IDL.Text,
  'timestamp' : Time,
});
export const Trait = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Blueprint = IDL.Record({
  'id' : IDL.Text,
  'doctrineManual' : IDL.Opt(IDL.Text),
  'traits' : IDL.Vec(Trait),
  'name' : IDL.Text,
  'lastModified' : Time,
});
export const Playbook = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'constraints' : IDL.Text,
  'content' : IDL.Text,
  'audience' : IDL.Text,
  'timestamp' : Time,
});
export const Assumption = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const Branch = IDL.Record({ 'name' : IDL.Text, 'rationale' : IDL.Text });
export const Scenario = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'timestamp' : Time,
  'assumptions' : IDL.Vec(Assumption),
  'branches' : IDL.Vec(Branch),
  'outcomeSummary' : IDL.Text,
});
export const TwinDraft = IDL.Record({
  'id' : IDL.Text,
  'response' : IDL.Text,
  'timestamp' : Time,
  'prompt' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'deleteArtifact' : IDL.Func([IDL.Text], [], []),
  'deleteBlueprint' : IDL.Func([IDL.Text], [], []),
  'deletePlaybook' : IDL.Func([IDL.Text], [], []),
  'deleteScenario' : IDL.Func([IDL.Text], [], []),
  'deleteTwinDraft' : IDL.Func([IDL.Text], [], []),
  'getAllArtifacts' : IDL.Func([], [IDL.Vec(Artifact)], ['query']),
  'getAllBlueprints' : IDL.Func([], [IDL.Vec(Blueprint)], ['query']),
  'getAllPlaybooks' : IDL.Func([], [IDL.Vec(Playbook)], ['query']),
  'getAllScenarios' : IDL.Func([], [IDL.Vec(Scenario)], ['query']),
  'getAllTwinDrafts' : IDL.Func([], [IDL.Vec(TwinDraft)], ['query']),
  'getArtifact' : IDL.Func([IDL.Text], [Artifact], ['query']),
  'getBlueprint' : IDL.Func([IDL.Text], [Blueprint], ['query']),
  'getPlaybook' : IDL.Func([IDL.Text], [Playbook], ['query']),
  'getScenario' : IDL.Func([IDL.Text], [Scenario], ['query']),
  'getTwinDraft' : IDL.Func([IDL.Text], [TwinDraft], ['query']),
  'saveArtifact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveBlueprint' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(Trait)], [], []),
  'savePlaybook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveScenario' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(Assumption), IDL.Text, IDL.Vec(Branch)],
      [],
      [],
    ),
  'saveTwinDraft' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'seedDemoData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Artifact = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'name' : IDL.Text,
    'timestamp' : Time,
  });
  const Trait = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const Blueprint = IDL.Record({
    'id' : IDL.Text,
    'doctrineManual' : IDL.Opt(IDL.Text),
    'traits' : IDL.Vec(Trait),
    'name' : IDL.Text,
    'lastModified' : Time,
  });
  const Playbook = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'constraints' : IDL.Text,
    'content' : IDL.Text,
    'audience' : IDL.Text,
    'timestamp' : Time,
  });
  const Assumption = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const Branch = IDL.Record({ 'name' : IDL.Text, 'rationale' : IDL.Text });
  const Scenario = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'timestamp' : Time,
    'assumptions' : IDL.Vec(Assumption),
    'branches' : IDL.Vec(Branch),
    'outcomeSummary' : IDL.Text,
  });
  const TwinDraft = IDL.Record({
    'id' : IDL.Text,
    'response' : IDL.Text,
    'timestamp' : Time,
    'prompt' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'deleteArtifact' : IDL.Func([IDL.Text], [], []),
    'deleteBlueprint' : IDL.Func([IDL.Text], [], []),
    'deletePlaybook' : IDL.Func([IDL.Text], [], []),
    'deleteScenario' : IDL.Func([IDL.Text], [], []),
    'deleteTwinDraft' : IDL.Func([IDL.Text], [], []),
    'getAllArtifacts' : IDL.Func([], [IDL.Vec(Artifact)], ['query']),
    'getAllBlueprints' : IDL.Func([], [IDL.Vec(Blueprint)], ['query']),
    'getAllPlaybooks' : IDL.Func([], [IDL.Vec(Playbook)], ['query']),
    'getAllScenarios' : IDL.Func([], [IDL.Vec(Scenario)], ['query']),
    'getAllTwinDrafts' : IDL.Func([], [IDL.Vec(TwinDraft)], ['query']),
    'getArtifact' : IDL.Func([IDL.Text], [Artifact], ['query']),
    'getBlueprint' : IDL.Func([IDL.Text], [Blueprint], ['query']),
    'getPlaybook' : IDL.Func([IDL.Text], [Playbook], ['query']),
    'getScenario' : IDL.Func([IDL.Text], [Scenario], ['query']),
    'getTwinDraft' : IDL.Func([IDL.Text], [TwinDraft], ['query']),
    'saveArtifact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveBlueprint' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(Trait)], [], []),
    'savePlaybook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveScenario' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(Assumption), IDL.Text, IDL.Vec(Branch)],
        [],
        [],
      ),
    'saveTwinDraft' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'seedDemoData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };